# This workflow will do a clean install of node dependencies, build the source code and run tests on Chrome Browser on our VM
name: Automation CI

on:
  #workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CICD-bvt:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2   
    
    - run: npm install
    
    - run: echo "install protractor"
